#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  7 10:53:43 2020

@author: jacob
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pathway = r'/home/jacob/Desktop/project-athena/task2/model_eval_results.csv'

results = pd.read_csv(pathway)
resultssplt = results['label'].str.split('-',3)

weakd = results[0:46]

for i in range(len(weakd)-1):
    weakd['label'][i+1]  = resultssplt[i+1][3]
    
task1 = results[46::]

ax1 = weakd.plot.barh(x='ae_type', y='accuracy',title = 'Accuracy of inndivudual ensmeble resuslts')
ax1.set_xlabel("Accuracy")
ax1.set_ylabel("Ensemble weak Defense")

ax2 = task1.plot.barh(x='label', y='accuracy',title = 'Accuracy of AEs from Task1')
ax2.set_xlabel("Accuracy")
ax2.set_ylabel("Task1 AE's")